version: "3.8"

services:
  api:
    container_name: "api"
    build:
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  mysql:
    container_name: mysql
    image: mysql:8.2.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
